Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using eProject.Models;
using eProject.Services;
using X.PagedList;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace eProject.Controllers
{
    public class ItemController : Controller
    {
        private IItemServices services;
        private IItemCategorySupplierServices iservices;
        private ICategoryServices cservices;
        private IRoleServices rservices;
        private ISupplierServices sservices;
        public ItemController(IItemServices services, IItemCategorySupplierServices iservices, ICategoryServices cservices, IRoleServices rservices, ISupplierServices sservices)
        {
            this.services = services;
            this.iservices = iservices;
            this.cservices = cservices;
            this.rservices = rservices;
            this.sservices = sservices;
        }
        public IActionResult Index(int? page, string itemName)
        {
            int pageSize = 4;
            int pageNumber = page ?? 1;
            if (string.IsNullOrEmpty(itemName))
            {
                var itemList = services.GetItems().ToPagedList(pageNumber, pageSize);
                ViewBag.data = itemList;
            }
            else
            {
                var itemList = services.GetItems().Where
                    (a => a.Description.Contains(itemName)).OrderByDescending(a => a.Price).ToList().ToPagedList(pageNumber, pageSize);
                ViewBag.data = itemList;
            }
            return View();
        }

        public IActionResult AdminIndexItem(string itemName)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    var listItem = services.GetItems();
                    if (string.IsNullOrEmpty(itemName))
                    {
                        return View(listItem);
                    }
                    else
                    {
                        listItem = services.GetItems().Where(i => i.Description.ToLower().Contains(itemName.ToLower())).ToList();
                        return View(listItem);
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        public IActionResult AdminDetailsItem(string itemCode)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    var model = iservices.GetItemCategorySupplier(itemCode);
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }


        [HttpGet]
        public IActionResult AdminCreateItem()
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    var listCategory = cservices.GetCategories().ToList();
                    ViewBag.listCat = new SelectList(listCategory, "Category_Id", "Description");
                    var listRole = rservices.GetRoles().ToList();
                    ViewBag.listRole = new SelectList(listRole, "Role_Id", "RoleName");
                    var listSup = sservices.GetSuppliers().ToList();
                    ViewBag.listSup = new SelectList(listSup, "SupplierCode", "SupplierName");
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult AdminCreateItem(Item newItem, IFormFile file)
        {
            //int cnt = 0;
            try
            {
                if (ModelState.IsValid)
                {
                    if (file.Length > 0)
                    {

                        var filepath = Path.Combine("wwwroot/images", file.FileName);
                        var stream = new FileStream(filepath, FileMode.Create);
                        file.CopyToAsync(stream);
                        newItem.Images = "images/" + file.FileName;
                        services.CreateItem(newItem);
                        //cnt = cnt + 1;
                        //TempData["cnt"] = cnt;
                        return RedirectToAction("AdminIndexItem");
                    }
                    else
                    {
                        ViewBag.Msg = "Cannot create new Item";
                    }
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
            }
            return View();
        }


        [HttpGet]
        public IActionResult AdminEditItem(string code)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    var model = services.GetItem(code);
                    var listCategory = cservices.GetCategories().ToList();
                    ViewBag.listCat = new SelectList(listCategory, "Category_Id", "Description");
                    var listRole = rservices.GetRoles().ToList();
                    ViewBag.listRole = new SelectList(listRole, "Role_Id", "RoleName");
                    var listSup = sservices.GetSuppliers().ToList();
                    ViewBag.listSup = new SelectList(listSup, "SupplierCode", "SupplierName");
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult AdminEditItem(Item editItem, IFormFile file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (file.Length > 0)
                    {
                        var filepath = Path.Combine("wwwroot/images", file.FileName);
                        var stream = new FileStream(filepath, FileMode.Create);
                        file.CopyToAsync(stream);
                        editItem.Images = "images/" + file.FileName;
                        services.UpdateItem(editItem);
                        return RedirectToAction("AdminIndexItem");
                    }
                    else
                    {
                        ViewBag.Msg = "Cannot update Item";
                    }
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
            }
            return View();
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using eProject.Services;
using eProject.Models;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace eProject.Controllers
{
    public class RoleController : Controller
    {
        private IRoleServices services;
        public RoleController(IRoleServices services)
        {
            this.services = services;
        }
        public IActionResult AdminIndexRole(string rname)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    var listRole = services.GetRoles();
                    if (string.IsNullOrEmpty(rname))
                    {
                        return View(listRole);
                    }
                    else
                    {
                        listRole = services.GetRoles().Where(r => r.RoleName.ToLower().Contains(rname.ToLower())).ToList();
                        return View(listRole);
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult AdminCreateRole()
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult AdminCreateRole(Role newRole)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    services.AddRole(newRole);
                    return RedirectToAction("AdminIndexRole");
                }
                else
                {
                    ViewBag.Msg = "Cannot create new Role";
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
            }
            return View();
        }

        [HttpGet]
        public IActionResult AdminEditRole(int id)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    var model = services.GetRole(id);
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult AdminEditRole(Role editRole)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    services.UpdateRole(editRole);
                    return RedirectToAction("AdminIndexRole");
                }
                else
                {
                    ViewBag.Msg = "Cannot update Role";
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
            }
            return View();
        }

        public IActionResult AdminDeleteRole(int id)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    services.DeleteRole(id);
                    return RedirectToAction("AdminIndexRole");
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
   s
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="~/notification/ikr.notification.css" rel="stylesheet" />
    <!-- Stylesheets -->
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href='~/vendor/unicons-2.0.1/css/unicons.css' rel='stylesheet'>
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">
    <link href="~/css/night-mode.css" rel="stylesheet">
    <link href="~/css/stylehome.css" rel="stylesheet" />
    <!-- Vendor Stylesheets -->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="~/vendor/OwlCarousel/assets/owl.carousel.css" rel="stylesheet">
    <link href="~/vendor/OwlCarousel/assets/owl.theme.default.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/vendor/semantic/semantic.min.css">

    @RenderSection("css", required: false)



</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper-vl">

        <!-- Navbar -->
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item">
                    <div id="noti_Container"></div>
                </li>

            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">

                <li class="nav-item dropdown">
                    <div class="header_cart order-1">
                        <a href="@Url.Action("Index", "Admin")" class="cart__btn t"> <i class="fa fa-user" style="font-size:11px"></i><span>Hi, @ViewBag.session</span></a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <div class="header_cart order-1">
                        <a href="@Url.Action("Logout", "User")" class="cart__btn t"><i class="fas fa-sign-out-alt" style="font-size:12px"></i><span>Log out</span></a>
                    </div>
                </li>
            </ul>

        </nav>

        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="Admin Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Welcome: @ViewBag.session</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Admin
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Users Management
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="User" asp-action="AdminIndexUser" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Users</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Role" asp-action="AdminIndexRole" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Roles</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Items Management
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Item" asp-action="AdminIndexItem" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Items</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Category" asp-action="AdminIndexCategory" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Categories</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Supplier" asp-action="AdminIndexSupplier" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Suppliers</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Department" asp-action="AdminIndexDepartment" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    Departments Management
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Request" asp-action="AdminIndexRequest" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Request Management
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Report" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Report
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="background-color:#fff">
            @*<div id="noti_Container"></div>*@
            @RenderBody()
            @*<div style="margin-left:1em">

                </div>*@
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2021 <a href="#">Group 2 FPT Aptech</a>.</strong>
            All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>

    <script src="~/notification/ikr.notificationPlugin.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#noti_Container").ikrNotificationSetup();
            $.ajax({
                type: "GET",
                dataType: "json",
                url: "/Notifications/GetNotifications",
                traditional: true,
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    var notifications = data;
                    $("#noti_Container").ikrNotificationCount({
                        NotificationList: notifications,
                        NotiFromPropName: "FromUserName",
                        ListTitlePropName: "Title",
                        ListBodyPropName: "Reason",
                        ControllerName: "Notifications",
                        ActionName: "AllNotifications"
                    });
                },
                error: function (xhr, status, error) {

                }
            });
        });
    </script>

</body>
</html>

<!-- Javascripts -->
<!--<script src="~/js/jquery-3.3.1.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/vendor/OwlCarousel/owl.carousel.js"></script>
<script src="~/vendor/semantic/semantic.min.js"></script>
<script src="~/js/jquery.countdown.min.js"></script>
<script src="~/js/custom.js"></script>
<script src="~/js/product.thumbnail.slider.js"></script>
<script src="~/js/offset_overlay.js"></script>-->

Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <img width="50%" src="~/dist/img/companyLogo.PNG" alt="Company Logo" class="brand-image img-circle elevation-3"
                 style="opacity: .8" />
        </div>
        <div>
            <h3 style="text-align: center; color: #2b2f4c" class="brand-text font-weight-light">HMT Technologies</h3>
        </div>
        <!-- /.login-logo -->
        @RenderBody()
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>

</body>
</html>

Views/Shared/_header.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        @*<li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>*@
        <li class="nav-item">
            <p></p>
            <div id="noti_Container"></div>
        </li>
    </ul>

    <!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="fa fa-user"></i> Hi, @ViewBag.session
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <div class="dropdown-item">
                <i class="nav-icon fas fa-envelope mr-2"></i>
                @Html.ActionLink("My Profile", "Details", "Admin", new { uname = ViewBag.session }, new { @style = "color:black" })
            </div>
            <div class="dropdown-divider"></div>
            <a asp-controller="Admin" asp-action="Logout" class="dropdown-item">
                <i class="nav-icon fas fa-sign-out-alt mr-2"></i> Logout
            </a>
        </div>
    </li>
    @*<li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
            <i class="fas fa-th-large"></i>
        </a>
    </li>*@
</ul>
</nav>