Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace eProject.Models
{
    public class Supplier
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string SupplierCode { get; set; }

        [Required(ErrorMessage = "SupplierName is required!")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "SupplierName from 1 to 50 chacracters!")]
        public string SupplierName { get; set; }

        [Required(ErrorMessage = "ContactName is required!")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "ContactName from 1 to 50 chacracters!")]
        public string ContactName { get; set; }

        [Required(ErrorMessage = "Phone is required!")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Phone from 1 to 20 chacracters!")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Status is required!")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Status from 1 to 20 chacracters!")]
        public string Status { get; set; }
    }
}

Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using eProject.Services;
using eProject.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace eProject.Controllers
{
    public class SupplierController : Controller
    {
        private ISupplierServices services;
        public SupplierController(ISupplierServices services)
        {
            this.services = services;
        }
        public IActionResult AdminIndexSupplier(string sname)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    var listSup = services.GetSuppliers();
                    if (string.IsNullOrEmpty(sname))
                    {
                        return View(listSup);
                    }
                    else
                    {
                        listSup = services.GetSuppliers().Where(s => s.SupplierName.ToLower().Contains(sname.ToLower())).ToList();
                        return View(listSup);
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult AdminCreateSupplier()
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult AdminCreateSupplier(Supplier newSupplier)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    services.AddSupplier(newSupplier);
                    return RedirectToAction("AdminIndexSupplier");
                }
                else
                {
                    ViewBag.Msg = "Cannot create new Supplier";
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
            }
            return View();
        }

        [HttpGet]
        public IActionResult AdminEditSupplier(string code)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    var model = services.GetSupplier(code);
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult AdminEditSupplier(Supplier editSupplier)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    services.UpdateSupplier(editSupplier);
                    return RedirectToAction("AdminIndexSupplier");
                }
                else
                {
                    ViewBag.Msg = "Cannot update Supplier";
                }
            }
            catch (Exception e)
            {
                ViewBag.Msg = e.Message;
            }
            return View();
        }

        public IActionResult AdminDeleteSupplier(string code)
        {
            string json_admin_session = HttpContext.Session.GetString("admin_session");
            JObject jsonResponseAdmin = null;
            Admins admin = null;
            if (json_admin_session != null)
            {
                //lấy session Admin
                jsonResponseAdmin = JObject.Parse(json_admin_session);
                admin = JsonConvert.DeserializeObject<Admins>(jsonResponseAdmin.ToString());

                if (admin != null)
                {
                    ViewBag.session = HttpContext.Session.GetString("username");
                    services.DeleteSupplier(code);
                    return RedirectToAction("AdminIndexSupplier");
                }
                else
                {
                    return RedirectToAction("Login", "Admin");
                }
            }
            return View();
        }
    }
}

Views/Supplier/AdminCreateSupplier.cshtml
@model eProject.Models.Supplier

@{
    ViewData["Title"] = "AdminCreateSupplier";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<div class="wrapper">
    <div class="gambo-Breadcrumb">
        <div class="container-fluit">
            <div class="row">
                <div class="col-md-10">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item active" aria-current="page"><a href="@Url.Action("AdminIndexSupplier", "Supplier")">Supplier List</a></li>
                            <li class="breadcrumb-item active" aria-current="page">/<a href="#">Create Supplier </a></li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>

    <div style="margin-left: 10px; margin-right: 10px">

        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="AdminCreateSupplier">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="SupplierCode" class="control-label"></label>
                        <input asp-for="SupplierCode" class="form-control" />
                        <span asp-validation-for="SupplierCode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SupplierName" class="control-label"></label>
                        <input asp-for="SupplierName" class="form-control" />
                        <span asp-validation-for="SupplierName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactName" class="control-label"></label>
                        <input asp-for="ContactName" class="form-control" />
                        <span asp-validation-for="ContactName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                        <input asp-for="Status" class="form-control" />
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="AdminIndexSupplier">Back to List</a>
            <h3 style="color:red">@ViewBag.Msg</h3>
        </div>

        </div>
</div>

Views/Supplier/AdminEditSupplier.cshtml
@model eProject.Models.Supplier

@{
    ViewData["Title"] = "AdminEditSupplier";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@{
    ViewData["Title"] = "AdminCreateDepartment";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<div class="wrapper">
    <div class="gambo-Breadcrumb">
        <div class="container-fluit">
            <div class="row">
                <div class="col-md-10">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item active" aria-current="page"><a href="@Url.Action("AdminIndexSupplier", "Supplier")">Supplier List</a></li>
                            <li class="breadcrumb-item active" aria-current="page">/<a href="#">Edit Supplier </a></li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>

    <div style="margin-left: 10px; margin-right: 10px">

        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="AdminEditSupplier">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="SupplierCode" />
                    <div class="form-group">
                        <label asp-for="SupplierName" class="control-label"></label>
                        <input asp-for="SupplierName" class="form-control" />
                        <span asp-validation-for="SupplierName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactName" class="control-label"></label>
                        <input asp-for="ContactName" class="form-control" />
                        <span asp-validation-for="ContactName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                        <input asp-for="Status" class="form-control" />
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="AdminIndexSupplier">Back to List</a>
            <h3 style="color:red">@ViewBag.Msg</h3>
        </div>

</div>
</div>

Views/Supplier/AdminIndexSupplier.cshtml
@model IEnumerable<eProject.Models.Supplier>

@{
    ViewData["Title"] = "AdminIndexSupplier";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@{
    ViewData["Title"] = "AdminCreateDepartment";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<div class="wrapper">
    <div class="gambo-Breadcrumb">
        <div class="container-fluit">
            <div class="row">
                <div class="col-md-10">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item active" aria-current="page"><a href="#">Supplier List</a></li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>

    <div style="margin-left: 10px; margin-right: 10px">
        <div class="text-center" style="padding:10px">
            @using (Html.BeginForm())
            {
                <input type="text" name="sname" placeholder="Enter supplier name..." />
                <input type="submit" value="Search" class="btn-info" />
            }
        </div>

        <p>
            <a asp-action="AdminCreateSupplier">Create New</a>
        </p>
        <table class="table table-bordered" border="1">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.SupplierCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SupplierName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ContactName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Phone)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.SupplierCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SupplierName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ContactName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Phone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "AdminEditSupplier", "Supplier", new { code = item.SupplierCode })|
                            @Html.ActionLink("Delete", "AdminDeleteSupplier", "Supplier", new { code = item.SupplierCode })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        </div>
</div>